---
- name: New Webserver
  hosts: all
  become: yes
  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted

  tasks:
    - name: install webserver software
      package:
        name: httpd
        state: present

    - name: Deploy HTML file
      copy:
        src: files/example.html
        dest: /var/www/html/index.html
        owner: apache
        owner: apache
        mode: 0644
      notify: restart httpd

    - name: open firewall port
      ansible.posix.firewalld:
        service: http
        permanent: yes
        state: enabled